#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# create local php.ini if it doesn't exist, set local timezone
if [[ ! -f /config/php/php-local.ini ]]; then
    printf "; Edit this file to override php.ini directives\\n\\ndate.timezone = %s\\n" "$TZ" >/config/php/php-local.ini
fi

# symlink user php-local.ini to image
rm -rf /etc/php81/conf.d/php-local.ini
ln -s /config/php/php-local.ini /etc/php81/conf.d/php-local.ini

# create override for www.conf if it doesn't exist
if [[ ! -f /config/php/www2.conf ]]; then
    printf "; Edit this file to override www.conf and php-fpm.conf directives and restart the container\\n\\n; Pool name\\n[www]\\n\\n" >/config/php/www2.conf
fi

# copy user www2.conf to image
cp /config/php/www2.conf /etc/php81/php-fpm.d/www2.conf
