#!/usr/bin/with-contenv bash

# remove old samples
find /config/nginx/ \
    -name "*.conf.sample" \
    -type f \
    -delete

# copy new samples
find /defaults/nginx/ \
    -maxdepth 1 \
    -name "*.conf.sample" \
    -type f \
    -exec cp "{}" /config/nginx/ +

[[ -d /defaults/nginx/http-confs/ ]] &&
    find /defaults/nginx/http-confs/ \
        -maxdepth 1 \
        -name "*.conf.sample" \
        -type f \
        -exec cp "{}" /config/nginx/http-confs/ +

[[ -d /defaults/nginx/location-confs/ ]] &&
    find /defaults/nginx/location-confs/ \
        -maxdepth 1 \
        -name "*.conf.sample" \
        -type f \
        -exec cp "{}" /config/nginx/location-confs/ +

[[ -d /defaults/nginx/server-confs/ ]] &&
    find /defaults/nginx/server-confs/ \
        -maxdepth 1 \
        -name "*.conf.sample" \
        -type f \
        -exec cp "{}" /config/nginx/server-confs/ +

[[ -d /defaults/nginx/site-confs/ ]] &&
    find /defaults/nginx/site-confs/ \
        -maxdepth 1 \
        -name "*.conf.sample" \
        -type f \
        -exec cp "{}" /config/nginx/site-confs/ +
