#!/usr/bin/with-contenv bash

# copy samples
cp \
    /defaults/nginx/*.conf.sample \
    /config/nginx/
cp \
    /defaults/nginx/http-confs/*.conf.sample \
    /config/nginx/http-confs/
cp \
    /defaults/nginx/location-confs/*.conf.sample \
    /config/nginx/location-confs/
cp \
    /defaults/nginx/server-confs/*.conf.sample \
    /config/nginx/server-confs/
cp \
    /defaults/nginx/site-confs/*.conf.sample \
    /config/nginx/site-confs/
cp \
    /defaults/nginx/subdomain-confs/*.conf.sample \
    /config/nginx/subdomain-confs/
cp \
    /defaults/nginx/subfolder-confs/*.conf.sample \
    /config/nginx/subfolder-confs/
