#!/usr/bin/with-contenv bash

# copy default config files if they don't exist
[[ ! -f /config/nginx/nginx.conf ]] && \
    cp /defaults/nginx/nginx.conf.sample /config/nginx/nginx.conf
[[ ! -f /config/nginx/site-confs/default.conf ]] && \
    cp /defaults/nginx/site-confs/default.conf.sample /config/nginx/site-confs/default.conf

# copy index.html if no index file exists
INDEX_EXISTS=false
for file in /config/www/index.*; do
    if [[ -e "${file}" ]]; then
        INDEX_EXISTS=true
        break
    fi
done
[[ ${INDEX_EXISTS} == false ]] && grep -Eq '^\s*index[^#]*index\.html' /config/nginx/**/*.conf && \
    cp /defaults/www/index.html /config/www/index.html

# copy pre-generated dhparams or generate if needed
[[ ! -f /config/nginx/dhparams.pem ]] && \
    cp /defaults/nginx/dhparams.pem /config/nginx/dhparams.pem
if ! grep -q 'PARAMETERS' "/config/nginx/dhparams.pem"; then
    curl -o /config/nginx/dhparams.pem -L "https://ssl-config.mozilla.org/ffdhe4096.txt"
fi

# Set resolver, ignore ipv6 addresses
if ! grep -q 'resolver' /config/nginx/http-confs/resolver.conf; then
    RESOLVERRAW=$(awk 'BEGIN{ORS=" "} $1=="nameserver" {print $2}' /etc/resolv.conf)
    for i in ${RESOLVERRAW}; do
        if [[ "$(awk -F ':' '{print NF-1}' <<< "${i}")" -le 2 ]]; then
            RESOLVER="${RESOLVER} ${i}"
        fi
    done
    if [[ -z "${RESOLVER}" ]]; then
        RESOLVER="127.0.0.11"
    fi
    echo "Setting resolver to ${RESOLVER}"
    RESOLVEROUTPUT="# This file is auto-generated only on first start, based on the container's /etc/resolv.conf file. Feel free to modify it as you wish.\n\nresolver ${RESOLVER} valid=30s;"
    echo -e "${RESOLVEROUTPUT}" > /config/nginx/http-confs/resolver.conf
    echo -e "${RESOLVEROUTPUT}" > /config/nginx/location-confs/resolver.conf
fi

# Set worker_processes
if ! grep -q 'worker_processes' /config/nginx/worker_processes.conf; then
    WORKER_PROCESSES=$(nproc)
    echo "Setting worker_processes to ${WORKER_PROCESSES}"
    echo -e "# This file is auto-generated only on first start, based on the cpu cores detected. Feel free to change it to any other number or to auto to let nginx handle it automatically.\n\nworker_processes ${WORKER_PROCESSES};" > /config/nginx/worker_processes.conf
fi
