#!/usr/bin/with-contenv bash

# create local php.ini if it doesn't exist, set local timezone
[[ ! -f /config/php/php-local.ini ]] && \
    printf "; Edit this file to override php.ini directives and restart the container\\n\\ndate.timezone = %s\\n" "$TZ" > /config/php/php-local.ini

# copy user php-local.ini to image
cp /config/php/php-local.ini /etc/php8/conf.d/php-local.ini

# create override for www.conf if it doesn't exist
[[ ! -f /config/php/www2.conf ]] && \
    printf "; Edit this file to override www.conf and php-fpm.conf directives and restart the container\\n\\n; Pool name\\n[www]\\n\\n" > /config/php/www2.conf

# copy user www2.conf to image
cp /config/php/www2.conf /etc/php8/php-fpm.d/www2.conf
