#!/usr/bin/with-contenv bash

# make our folders
mkdir -p \
    /config/{nginx/site-confs,www,log/nginx,keys,log/php,php} \
    /run \
    /var/lib/nginx/tmp/client_body \
    /var/tmp/nginx

# copy config files
[[ ! -f /config/nginx/nginx.conf ]] && \
    cp /defaults/nginx.conf /config/nginx/nginx.conf
[[ ! -f /config/nginx/ssl.conf ]] && \
    cp /defaults/ssl.conf /config/nginx/ssl.conf
[[ ! -f /config/nginx/site-confs/default ]] && \
    cp /defaults/default /config/nginx/site-confs/default
[[ $(find /config/www -type f | wc -l) -eq 0 ]] && \
    cp /defaults/index.html /config/www/index.html

# backwards compatibility for alpine >=3.14
if [ ! -e /etc/nginx/conf.d ]; then
    ln -s /etc/nginx/http.d /etc/nginx/conf.d
fi

# permissions
chown -R abc:abc \
    /config \
    /var/lib/nginx \
    /var/tmp/nginx
chmod -R g+w \
    /config/{nginx,www}
chmod -R 644 /etc/logrotate.d
