#!/usr/bin/with-contenv bash

# permissions
chown -R abc:abc \
    /var/lib/nginx \
    /var/tmp/nginx

chown -R abc:abc \
    /config/keys \
    /config/nginx \
    /config/php

chown abc:abc \
    /config/www \
    /config/log

chmod -R g+w \
    /config/nginx

chmod -R 644 /etc/logrotate.d

if [[ -f "/config/log/logrotate.status" ]]; then
    chmod 600 /config/log/logrotate.status
fi
