#!/usr/bin/with-contenv bash
SUBJECT="//C=US/ST=CA/L=Carlsbad/O=Linuxserver.io/OU=LSIO Server/CN=*"
if [[ -f /config/keys/self-signed/cert.key && -f /config/keys/self-signed/cert.crt ]]; then
echo "using keys found in /config/keys/self-signed"
else
echo "generating self-signed keys in /config/keys/self-signed, you can replace these with your own keys if required"
openssl req -new -x509 -days 3650 -nodes -out /config/keys/self-signed/cert.crt -keyout /config/keys/self-signed/cert.key -subj "$SUBJECT"
fi


