#!/usr/bin/with-contenv bash

active_confs=$(find /config/nginx/ -name "*.conf" -type f 2>/dev/null)

for i in ${active_confs}; do
    if [ -f "${i}.sample" ]; then
        if [ "$(sed -nE 's|^## Version ([0-9]{4}\/[0-9]{2}\/[0-9]{2}).*|\1|p' "${i}")" != "$(sed -nE 's|^## Version ([0-9]{4}\/[0-9]{2}\/[0-9]{2}).*|\1|p' "${i}.sample")" ]; then
            active_confs_changed="${i}\n${active_confs_changed}"
        fi
    fi
done

if [ -n "${active_confs_changed}" ]; then
    echo "**** The following active confs have different version dates than the samples that are shipped. ****"
    echo "**** This may be due to user customization or an update to the samples. ****"
    echo "**** You should compare the following files to the samples in the same folder and update them. ****"
    echo "**** Use the link at the top of the file to view the changelog. ****"
    echo -e "${active_confs_changed}"
fi
